apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcp-weather-app-auth
spec:
  tls:
    - hosts:
        - weather-auth.192.168.49.2.nip.io
  rules:
    - host: weather-auth.192.168.49.2.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcp-weather-auth-service
                port:
                  number: 8080
