apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flowise
  namespace: flowise
spec:
  tls:
    - hosts:
        - flowise.CHANGEME.nip.io
  rules:
    - host: flowise.CHANGEME.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flowise
                port:
                  number: 3000
